---
server:
  port: 8080
  contextPath: /SpringBootCRUDApp
---
spring:
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:oracle:thin://localhost:1521:ORCL
    username: nexus
    password: l0bst3r
    driverClassName: oracle.jdbc.OracleDriver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.Oracle10gDialect

